config/routes.rb
OutfitRails::Application.routes.draw do

  resources :relationships

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"
  get "home", to: 'users#profile', as: 'home'
  get "search", to: 'posts#search', as: 'search'
  get "favorites", to: 'users#show_favorites', as: 'favorites'
  get "following", to: 'users#show_following', as: 'following'
  get "followers", to: 'users#show_followers', as: 'followers'
  resources :posts do
    get "crop", on: :member
    get "tag", on: :member
    put :favorite, on: :member
    resources :comments
  end

  resources :users

  root 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :name, presence: true
    validates :username, uniqueness: true, presence: true
    validates :email, uniqueness: true, presence: true, format: { with: /\A[\w.+-]+@([\w]+.)+\w+\Z/ }
    before_validation :prep_email
    before_save :create_avatar_url
    has_many :posts
    has_many :favorite_posts # Relationship
    has_many :favorites, through: :favorite_posts, source: :post # Actual posts favorited.
    has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id"
    has_many :followed_relationships, class_name: "Relationship", foreign_key: "follower_id"
    has_many :followers, through: :follower_relationships
    has_many :followeds, through: :followed_relationships

    def following? user
        self.followeds.include? user
    end

    def follow user
        Relationship.create follower_id: self.id, followed_id: user.id
    end


    private

    def prep_email
        self.email = self.email.strip.downcase if self.email
    end

    def create_avatar_url
        self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # PROBABLY NOT NEEDED
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # PUBLIC PROFILE PAGE
  # GET /users/1
  # GET /users/1.json
  def show
    @post = Post.new
    @relationship = Relationship.where(
      follower_id: current_user.id,
      followed_id: @user.id
    ).first_or_initialize if current_user
  end

  def show_favorites
  end

  # SIGNUP PAGE
  # GET /users/new
  def new
    if current_user
      redirect_to home_path
    else
      @user = User.new
    end
  end

  # SETTINGS EDIT PAGE
  # GET /users/1/edit
  def edit
  end

  # GET LIST OF POSTS OF FOLLOWED USERS
  #
  def profile
    if current_user
      @post = Post.new
      friend_ids = current_user.followeds.map(&:id).push(current_user.id)
      @posts = Post.find_all_by_user_id(friend_ids)
    else
      redirect_to root_url
    end
  end

  # POST SIGNUP
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'Account registered!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # SETTINGS UPDATE
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE USER
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :password, :password_confirmation, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form-signin" } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class="form-signin-heading">New user</h1>
  <%= f.text_field :email, class: "form-control", placeholder: "Email address" %>
  <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
  <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password again" %>

  <%= f.submit "Create Account", class: "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/users/_profile_menu.html.erb
<% content_for(:head) do %>
  <%= stylesheet_link_tag "typeahead.js-bootstrap" %>
<% end %>

<div class="col-md-2">
  <div class="well sidebar-nav">
    <ul class="nav nav-pills nav-stacked">
      <li><a href="<%= user_path current_user %>">
        <img class="img-thumbnail" src="<%= current_user.avatar_url %>"> <%= current_user.name %> (@<%= current_user.username %>)</a></li>
      <li class=<%= page=="follows" ? "active" : "" %>><a href="<%= following_path %>"><span class="glyphicon glyphicon-eye-open"></span> Following (<%= current_user.followeds.count %>)</a></li>
      <li class=<%= page=="followers" ? "active" : "" %>><a href="<%= followers_path %>"><span class="glyphicon glyphicon-user"></span> Followers (<%= current_user.followers.count %>)</a></li>
      <li class=<%= page=="favorites" ? "active" : "" %>><a href="<%= favorites_path %>"><span class="glyphicon glyphicon-heart"></span> Favorites (<%= current_user.favorites.count %>)</a></li>
      <li class=<%= page=="find" ? "active" : "" %>>
        <form action="<%= search_path %>" method="get">
          <span class="glyphicon glyphicon-search"></span>
          <%= search_field_tag :q, params[:q], class: 'typeahead form-control find-type' %>
          <%= submit_tag "Search", name: nil %>
        </form>
      </li>
      <li><a href="<%= new_post_path %>"><span class="glyphicon glyphicon-edit"></span> Post</a></li>
      <!-- <li><a href="#">Trending</a></li> -->
    </ul>
  </div><!--/.well -->
</div><!--/span-->


<% content_for(:footer) do %>
  <%= javascript_include_tag "typeahead.min" %>
  <script type="text/javascript">
    $(function(){
      $('.find-type').typeahead({
        name: 'posts',
        remote: {
          url: '/search.json?q=%QUERY',
          filter: lightwell
        }
      });

      function lightwell(parsedResponse) {
        var i, l, obj, matches = [];

        if (parsedResponse.term==="") {
            return;
        }

        for  (i = 0, l = parsedResponse.length; i<l; i++) {
            obj = parsedResponse[i];
            matches.push(obj.message);
            matches.push(obj.user.username);
        }
        return(matches);
      }
    });
  </script>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% @users.each do |user| %>
  <a href="<%= user_path user %>">
    <img src="<%= user.avatar_url %>">
    <%= user.name %>
  </a>
  @<%= user.username %>
  <p>
    <%= user.posts.size %> Posts <br>
    <%= user.followers.count %> Followers <br>
    <%= user.followeds.count %> Following <br>
  </p>
  <% if user.posts.first %>
    <p><%= user.posts.first.message %></p>
  <% end %>
<br>
<% end %>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<div class="row">
  <%= render partial: "profile_menu", locals: {page: ""}%>

  <div class="coverflow col-md-10">
    <div class="flowItem">
      <div class="well">
        <%= image_tag "cats1.jpg", alt: "Cat1", class: "img-responsive itemImage" %>
        <ul class="list-unstyled list-inline share-row">
          <li><a class="btn btn-default" href="#TODO">Comment &raquo;</a></li>
          <li class="pull-right"><a class="btn btn-default" href="#TODO"><span class="glyphicon glyphicon-eye-open"></span></a></li>
          <li class="pull-right"><a class="btn btn-default" href="#TODO"><span class="glyphicon glyphicon-heart"></span></a></li>
        </ul>
      </div>
    </div>
    <div class="flowItem">
      <div class="well">
        <%= image_tag "cats2.jpg", alt: "Cat2", class: "img-responsive img-rounded itemImage" %>
        <ul class="list-unstyled list-inline share-row">
          <li><a class="btn btn-default" href="#TODO">Comment &raquo;</a></li>
          <li class="pull-right"><a class="btn btn-default" href="#TODO"><span class="glyphicon glyphicon-eye-open"></span></a></li>
          <li class="pull-right"><a class="btn btn-default" href="#TODO"><span class="glyphicon glyphicon-heart"></span></a></li>
        </ul>
      </div>
    </div>
    <div class="flowItem">
      <div class="well">
        <%= image_tag "cats3.jpg", alt: "Cat3", class: "img-responsive itemImage" %>
        <ul class="list-unstyled list-inline share-row">
          <li><a class="btn btn-default" href="#TODO">Comment &raquo;</a></li>
          <li class="pull-right"><a class="btn btn-default" href="#TODO"><span class="glyphicon glyphicon-eye-open"></span></a></li>
          <li class="pull-right"><a class="btn btn-default" href="#TODO"><span class="glyphicon glyphicon-heart"></span></a></li>
        </ul>
      </div>
    </div>
  </div><!-- end coverflow -->
</div><!-- end row -->

<hr>



<h1>Feed</h1>
<% @posts.each do |post| %>
  <a href="<%= user_path post.user %>">
    <img src="<%= post.user.avatar_url %>">
    <%= post.user.name %>
  </a>
  @<%= post.user.username %>
  <%= time_ago_in_words(post.created_at) %>
  <div style="position:relative;">
    <%= image_tag post.outfit.url(:profile), class: "img-responsive" %>
    <% post.outfit_tags.each do |tag| %>
      <div class="tagInput" style="top:<%= tag.y_loc %>px;
        left:<%= tag.x_loc %>px;">
        <span class="input-group-addon glyphicon glyphicon-tag"></span>
        <%= tag.content %>
      </div>
    <% end %>
  </div>
  <p><%= raw auto_link(post.message) %></p>
  <p>
    <% if current_user.favorites.include?(post) %>
      <%= link_to "unfavorite", favorite_post_path(post, type: 'unfavorite'), method: :put %>
    <% else %>
      <%= link_to "favorite", favorite_post_path(post, type: 'favorite'), method: :put %>
    <% end %>
  </p>
<% end %>

<script>
  $(function(){
    transformCovers();
    $('.coverflow').on('click','.flowItem:not(.selected)',function(){
      transformCovers($(this));
    });
  });

  function transformCovers(centerItem,callback) {
    if(typeof(centerItem)=="undefined"){
      var items = $('.coverflow .flowItem');
      centerItem = items.eq(parseInt(items.length/2));
    }

    if(!centerItem.hasClass('selected')){
      var leftItems = centerItem.prevAll('.flowItem');
      var rightItems = centerItem.nextAll('.flowItem');

      var transform_vals = "translateX(0) translateZ(0)";
      centerItem.css({"transform": transform_vals});

      leftItems.each(function(i){
        var itemdelta = i+1;
        var transform_vals = "translateX("+((itemdelta)*-100)+"%) translateZ(-200px)";
        $(this).css({"transform": transform_vals});
      });

      rightItems.each(function(i){
        var itemdelta = i+1;
        var transform_vals = "translateX("+((itemdelta)*100)+"%)  translateZ(-200px)";
        $(this).css({"transform": transform_vals});
      });

   centerItem.addClass('selected').siblings('.selected').removeClass('selected');
    }
  }
</script>

app/views/users/show.html.erb
<% if current_user %>
<h1>Post an Outfit</h1>
<p>
    <%= render 'posts/form' %>
</p>
<% end %>

<img class="avatar" src="<%= @user.avatar_url %>">
<h1><%= @user.name %></h1>
<p>
  <strong>@<%= @user.username %></strong>
</p>
<p>
    <%= @user.posts.size %> Posts <br>
    <%= @user.followers.count %> Followers <br>
    <%= @user.followeds.count %> Following
</p>
<% if current_user and @user != current_user %>
    <% if current_user.following? @user %>
        <%= form_tag relationship_path, method: :delete do %>
            <%= submit_tag "Unfollow" %>
        <% end %>
    <% else %>
        <%= form_for @relationship do %>
            <%= hidden_field_tag :followed_id, @user.id %>
            <%= submit_tag "Follow" %>
        <% end %>
    <% end %>
<% end %>

<h1>Posts</h1>
<% @user.posts.each do |post| %>
    <a href="<%= post_path post %>">
        <img class="avatar" src="<%= @user.avatar_url %>">
        <strong><%= @user.name %></strong>
        @<%= @user.username %>
        <%= time_ago_in_words(post.created_at) %><br>
        <p>
          <%= image_tag post.outfit.url %>
        </p>
        <p> <%= post.message %> </p>
    </a>
<% end %>




<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_favorites.html.erb
<div class="row-fluid">
  <%= render partial: "profile_menu", locals: {page: "favorites"}%>

  <h1>Favorites</h1>
  <% current_user.favorites.each do |post| %>
    <a href="<%= user_path post.user %>">
      <img src="<%= post.user.avatar_url %>">
      <%= post.user.name %>
    </a>
    @<%= post.user.username %>
    <%= time_ago_in_words(post.created_at) %>
    <p><%= post.message %></p>
    <p>
      <% if current_user.favorites.include?(post) %>
        <%= link_to "unfavorite", favorite_post_path(post, type: 'unfavorite'), method: :put %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/users/show_followers.html.erb
<div class="row-fluid">
  <%= render partial: "profile_menu", locals: {page: "followers"}%>

  <h1>Followers</h1>
  <% current_user.followers.each do |follower| %>
    <a href="<%= user_path follower %>">
      <img src="<%= follower.avatar_url %>">
      <%= follower.name %>
    </a>
    @<%= follower.username %>
  <% end %>
</div>

app/views/users/show_following.html.erb
<div class="row-fluid">
  <%= render partial: "profile_menu", locals: {page: "following"}%>

  <h1>Following</h1>
  <% current_user.followeds.each do |followed| %>
    <a href="<%= user_path followed %>">
      <img src="<%= followed.avatar_url %>">
      <%= followed.name %>
    </a>
    @<%= followed.username %>
  <% end %>
</div>