config/routes.rb
OutfitRails::Application.routes.draw do

  resources :relationships

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"
  get "home", to: 'users#profile', as: 'home'
  get "search", to: 'posts#search', as: 'search'
  get "favorites", to: 'users#show_favorites', as: 'favorites'
  get "following", to: 'users#show_following', as: 'following'
  get "followers", to: 'users#show_followers', as: 'followers'
  resources :posts do
    get "crop", on: :member
    get "tag", on: :member
    put :favorite, on: :member
    resources :comments
  end

  resources :users

  root 'users#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OutfitRails</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", media: "all" %>
  <style>
      body {
          padding-top: 50px;
          padding-bottom: 20px;
      }
  </style>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Outfit", home_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Public Profiles", users_path %></li>
          <li><%= link_to "My Profile", current_user %></li>
          <li><%= link_to "Public Posts", posts_path %></li>
          <li><%= link_to "Log Out", sessions_destroy_path %></li>
        <% else %>
      </ul>
          <%= form_tag sessions_create_path, class: "navbar-form navbar-right" do %>
            <div class="form-group">
              <%= text_field_tag :username, nil, placeholder: "username", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= password_field_tag :password, nil, placeholder: "password", class: "form-control" %>
            </div>
            <%= submit_tag "Log In", class: "btn btn-success" %>
          <% end %>
        <% end %>
    </div><!--/.nav-collapse -->
  </div>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "flash #{name}" %>
<% end %>

<div class="container">

  <%= yield %>

</div> <!-- /container -->

<footer>
  <%= yield(:footer) %>
  <p>&copy; Company 2012</p>
</footer>

</body>
</html>